name: google_map_location_picker
description: "ðŸŒ Map location picker for flutter Based on google_maps_flutter"
version: 4.1.7

#  flutter pub pub publish --dry-run
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  google_maps_flutter: ^2.0.1
  geolocator: ^7.7.1
  android_intent: ^2.0.2
  provider: ^5.0.0
  http: ^0.13.4
  stack_trace: ^1.10.0
  package_info: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.humazed.google_map_location_picker
        pluginClass: GoogleMapLocationPickerPlugin

flutter_intl:
  enabled: true
